### ISSUE TITLE
Exception thrown in validation as result of duplicated rdfIDs in an IGM

### ISSUE THREAD

**Issue by maja-r-m** [rte-france/cgmes-ocl-validator#24]
Used:
-validator built on 22.05.2020. 3:32AM GMT+2
- ecore from 19.05.2020 https://entsoe.sharefile.com/f/fo5ae7c8-0aaf-4703-bb74-03053f249ff5
- CEPS IGM from https://entsoe.sharefile.com/f/foc37c65-daea-4b33-a05d-140149e16cd6

Behavior:
Generated excelReport is empty.

cmd track:
------------------------------------------------------------------------------------------------
D:\OCL\ocl_validator-2.1>set INPUTS=inputs

D:\OCL\ocl_validator-2.1>set VALIDATOR_HOME=.

D:\OCL\ocl_validator-2.1>set VALIDATOR_CONFIG=config

D:\OCL\ocl_validator-2.1>chcp 65001
Active code page: 65001

D:\OCL\ocl_validator-2.1>java -Xms1g -cp target/ocl_validator-2.1-jar-with-all-dependencies.jar ocl.OCLEvaluator inputs
[2020-05-22 14:02:15] [INFO   ] Reordering done!
[2020-05-22 14:02:15] [INFO   ] Transformed:20200513T0930Z_1D_CEPS_SV_001.xml
[2020-05-22 14:02:15] [INFO   ] XMI transformation done!
[2020-05-22 14:02:15] [INFO   ] Validator ready
[2020-05-22 14:02:16] [INFO   ] Start Validation
org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Feature 'open' not found. (file:///D:/OCL/ocl_validator-2.1/0c713e40-0150-45d8-abed-eba00d1695d9, 4997, 319)
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors(XMLLoadImpl.java:77)
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:185)
        at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
        at ocl.Validation.evaluate(Validation.java:149)
        at ocl.Validation.main(Validation.java:258)
Caused by: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'open' not found. (file:///D:/OCL/ocl_validator-2.1/0c713e40-0150-45d8-abed-eba00d1695d9, 4997, 319)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.reportUnknownFeature(XMLHandler.java:2045)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleUnknownFeature(XMLHandler.java:2009)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.handleUnknownFeature(XMIHandler.java:172)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.setAttribValue(XMLHandler.java:2761)
        at org.eclipse.emf.ecore.xmi.impl.SAXXMIHandler.handleObjectAttribs(SAXXMIHandler.java:79)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectFromFactory(XMLHandler.java:2247)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectFromTypeName(XMLHandler.java:2150)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObject(XMLHandler.java:2085)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.createObject(XMIHandler.java:151)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleFeature(XMLHandler.java:1894)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1048)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:82)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
        ... 4 more
[2020-05-22 14:02:18] [INFO   ] End Validation
[2020-05-22 14:02:18] [INFO   ] Creating reports...
[2020-05-22 14:02:18] [INFO   ] All excel reports created
[2020-05-22 14:02:18] [INFO   ] Excel created: inputs\DebugReport.xlsx
[2020-05-22 14:02:18] [INFO   ] Cache cleaned

D:\OCL\ocl_validator-2.1>PAUSE
Press any key to continue . . .
------------------------------------------------------------------------------------------------
Potential issue:
IGM has duplicated rdfIDs

Expected behavior:
Generated excelReport contains IDuniqueness error.

**Comment by maja-r-m** [comment]
Identified IDUniqueness issues are attached.
[IDuniqueness.xlsx](https://github.com/rte-france/cgmes-ocl-validator/files/4668560/IDuniqueness.xlsx)

**Comment by marcochiaramello** [comment]
A new class is introduced to treat cases for which the xmi is impossible, e.g. the ones breaking the xml/rdf consistency. If the case, the json containing the broken rules are written immediately in the cache directory, without any further validation. These cases are then treated as any other when writing the excel reports.
